---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus:   2

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[easy_rvm::_test_everything]
    attributes:
