name             'easy_rvm'
maintainer       'Zach Campbell'
maintainer_email 'zcampbell@1000bulbs.com'
license          'All rights reserved'
description      'Installs/Configures easy_rvm'
long_description 'Installs/Configures easy_rvm'
version          '0.1.0'
